test: &default

  # Credentials for REST APIs
  client_id: AUQZy-ngQgIUDn72-QH7INeCeNSHHyEX0S1jb2oHBanYoDxSsIsBUzyZSR0nENtAUHqUUDRn5auBzaSB
  #EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
  client_secret: EAKgXo7NwRhm64ApZwul-tgz85EEbskRcPjgoOLHUyTCk8lhiqa5pEIb2gqk-pU3XzSvCjjvjiZ0PL7Z

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: viktoriiabeznisko@gmail.com #Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
